version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: looopback_mongodb
    # hostname: looopback_mongo
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: 123456
    
    